name: conda_env
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - bioconda::samtools=1.17
  - conda-forge::r-base=4.2.3
  - conda-forge::r-optparse=1.7.3
  - conda-forge::r-dplyr=1.1.2
  - conda-forge::r-tidyr=1.2.0
  - conda-forge::r-readr=2.1.4
  - conda-forge::r-stringr=1.5.0
  - conda-forge::r-randomforest=4.7_1.1
  - pip
  - pip:
    - poetry